export interface GhanaLocation {
    region: string;
    towns: string[];
}

export const ghanaRegions: GhanaLocation[] = [
    {
        region: "Greater Accra",
        towns: [
            "Accra Central",
            "Achimota",
            "Adabraka",
            "Adenta",
            "Airport Residential Area",
            "Amasaman",
            "Ashiaman",
            "Ashaley Botwe",
            "Asylum Down",
            "Atomic",
            "Baatsona",
            "Cantonment",
            "Community 1",
            "Community 18",
            "Community 20",
            "Community 25",
            "Dansoman",
            "Darkuman",
            "Dome",
            "East Legon",
            "Gbawe",
            "Haatso",
            "James Town",
            "Kaneshie",
            "Kasoa",
            "Kpone",
            "Kwabenya",
            "Labadi",
            "Labone",
            "Lapaz",
            "Legon",
            "Madina",
            "Mallam",
            "Mamprobi",
            "McCarthy Hill",
            "Nima",
            "North Kaneshie",
            "North Legon",
            "Nungua",
            "Osu",
            "Pokuase",
            "Roman Ridge",
            "Sakumono",
            "Spintex",
            "Taifa",
            "Tema",
            "Teshie",
            "Tesano",
            "Tudu",
            "Weija",
            "West Legon",
        ],
    },
    {
        region: "Ashanti",
        towns: [
            "Abuakwa",
            "Adum",
            "Afrancho",
            "Agogo",
            "Ahodwo",
            "Anloga",
            "Anwiam",
            "Asafo",
            "Asokwa",
            "Atonsu",
            "Ayeduase",
            "Ayigya",
            "Bantama",
            "Bekwai",
            "Boadi",
            "Bohyen",
            "Bosomtwe",
            "Ejisu",
            "Emena",
            "Feyiase",
            "Fumesua",
            "Kaase",
            "Kenyasi",
            "Konongo",
            "Kumasi",
            "Kwadaso",
            "Mampong",
            "Manhyia",
            "Obuasi",
            "Santasi",
            "Tafo",
            "Tanoso",
        ],
    },
    {
        region: "Western",
        towns: [
            "Aboso",
            "Agona Nkwanta",
            "Ahanta West",
            "Axim",
            "Bogoso",
            "Daboase",
            "Effiekuma",
            "Elubo",
            "Enchi",
            "Essikado",
            "Half Assini",
            "Kojokrom",
            "Kwesimintsim",
            "Prestea",
            "Princess Town",
            "Sekondi",
            "Shama",
            "Takoradi",
            "Tarkwa",
            "Wassa Akropong",
        ],
    },
    {
        region: "Central",
        towns: [
            "Abakrampa",
            "Abura Dunkwa",
            "Agona Swedru",
            "Anomabo",
            "Apam",
            "Assin Fosu",
            "Cape Coast",
            "Dunkwa-On-Offin",
            "Elmina",
            "Kasoa",
            "Komenda",
            "Mankessim",
            "Mumford",
            "Nyakrom",
            "Saltpond",
            "Winneba",
        ],
    },
    {
        region: "Eastern",
        towns: [
            "Abetifi",
            "Abomosu",
            "Aburi",
            "Akim Oda",
            "Akim Swedru",
            "Akropong",
            "Akwatia",
            "Asamankese",
            "Asiakwa",
            "Begoro",
            "Coaltar",
            "Koforidua",
            "Kibi",
            "Kpeve",
            "Mpraeso",
            "New Abirem",
            "Nkawkaw",
            "Nsawam",
            "Oda",
            "Suhum",
        ],
    },
    {
        region: "Volta",
        towns: [
            "Adaklu",
            "Adidome",
            "Aflao",
            "Akatsi",
            "Anloga",
            "Ave Dakpa",
            "Denu",
            "Ho",
            "Hohoe",
            "Keta",
            "Kete Krachi",
            "Kpando",
            "Sogakope",
            "Tongu",
            "Tsito",
            "Vane",
        ],
    },
    {
        region: "Northern",
        towns: [
            "Bimbilla",
            "Bole",
            "Buipe",
            "Damongo",
            "Gambaga",
            "Gushiegu",
            "Kpandae",
            "Saboba",
            "Salaga",
            "Savelugu",
            "Tamale",
            "Tolon",
            "Walewale",
            "Yendi",
            "Zabzugu",
        ],
    },
    {
        region: "Upper East",
        towns: [
            "Bawku",
            "Bolgatanga",
            "Bongo",
            "Navrongo",
            "Paga",
            "Sandema",
            "Tongo",
            "Zebilla",
        ],
    },
    {
        region: "Upper West",
        towns: [
            "Funsi",
            "Gwollu",
            "Hamile",
            "Jirapa",
            "Kaleo",
            "Lambusie",
            "Lawra",
            "Nadowli",
            "Tumu",
            "Wa",
        ],
    },
    {
        region: "Bono",
        towns: [
            "Berekum",
            "Dormaa Ahenkro",
            "Duayaw Nkwanta",
            "Kintampo",
            "Sunyani",
            "Wenchi",
        ],
    },
    {
        region: "Bono East",
        towns: [
            "Atebubu",
            "Ejura",
            "Jema",
            "Kintampo",
            "Nkoranza",
            "Prang",
            "Techiman",
            "Yeji",
        ],
    },
    {
        region: "Ahafo",
        towns: [
            "Acherensua",
            "Bechem",
            "Duayaw Nkwanta",
            "Goaso",
            "Hwidiem",
            "Kenyasi",
            "Kukuom",
            "Mim",
        ],
    },
    {
        region: "Western North",
        towns: [
            "Aowin",
            "Bibiani",
            "Bodi",
            "Juaboso",
            "Sefwi Wiawso",
            "Suaman",
        ],
    },
    {
        region: "Savannah",
        towns: [
            "Bole",
            "Damongo",
            "Salaga",
            "Sawla",
            "Tolon",
            "Yapei",
        ],
    },
    {
        region: "North East",
        towns: [
            "Gambaga",
            "Nalerigu",
            "Walewale",
        ],
    },
    {
        region: "Oti",
        towns: [
            "Dambai",
            "Jasikan",
            "Kadjebi",
            "Kete Krachi",
            "Nkwanta",
        ],
    },
];

export const getRegions = (): string[] => {
    return ghanaRegions.map((location) => location.region).sort();
};

export const getTownsByRegion = (region: string): string[] => {
    const location = ghanaRegions.find((loc) => loc.region === region);
    return location ? location.towns.sort() : [];
};
